version: '3'
services:
  namenode:
    image: lsyeup1206/hadoop_cluster_namenode:latest
    container_name: namenode
    networks:
      - hadoop_cluster_net
    hostname: hadoop-cluster-namenode
    ports:
      - "9870:9870"
      - "9864:9864"
      - "8088:8088"
    # command: sh -c ./entrypoint.sh

  datanode1:
    image: lsyeup1206/hadoop_cluster_datanode:latest
    container_name: datanode1
    networks:
      - hadoop_cluster_net

  datanode2:
    image: lsyeup1206/hadoop_cluster_datanode:latest
    container_name: datanode2
    networks:
      - hadoop_cluster_net

  datanode3:
    image: lsyeup1206/hadoop_cluster_datanode:latest
    container_name: datanode3
    networks:
      - hadoop_cluster_net

networks:
  hadoop_cluster_net:
    driver: bridge
